apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: unstructured-data-controller
  name: unstructured-controller-manager-test
  namespace: unstructured-controller-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: unstructured-data-controller
  name: unstructured-leader-election-role-test
  namespace: unstructured-controller-namespace
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: unstructured-manager-role-test
  namespace: unstructured-controller-namespace
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - chunksgenerators
  - controllerconfigs
  - destinationsyncers
  - documentprocessors
  - sourcecrawlers
  - unstructureddatapipelines
  - vectorembeddingsgenerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - chunksgenerators/finalizers
  - controllerconfigs/finalizers
  - destinationsyncers/finalizers
  - documentprocessors/finalizers
  - sourcecrawlers/finalizers
  - unstructureddatapipelines/finalizers
  - vectorembeddingsgenerators/finalizers
  verbs:
  - update
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - chunksgenerators/status
  - controllerconfigs/status
  - destinationsyncers/status
  - documentprocessors/status
  - sourcecrawlers/status
  - unstructureddatapipelines/status
  - vectorembeddingsgenerators/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: unstructured-data-controller
  name: unstructured-leader-election-rolebinding-test
  namespace: unstructured-controller-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: unstructured-leader-election-role-test
subjects:
- kind: ServiceAccount
  name: unstructured-controller-manager-test
  namespace: unstructured-controller-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: unstructured-data-controller
  name: unstructured-manager-rolebinding-test
  namespace: unstructured-controller-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: unstructured-manager-role-test
subjects:
- kind: ServiceAccount
  name: unstructured-controller-manager-test
  namespace: unstructured-controller-namespace
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: unstructured-data-controller
    control-plane: controller-manager
  name: unstructured-controller-manager-service-test
  namespace: unstructured-controller-namespace
spec:
  ports:
  - name: https
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/name: unstructured-data-controller
    control-plane: controller-manager
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubernetes.io/reclaimPolicy: Delete
  name: unstructured-datastore-cache-test
  namespace: unstructured-controller-namespace
spec:
  accessModes:
  - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: unstructured-data-controller
    control-plane: controller-manager
  name: unstructured-controller-manager-test
  namespace: unstructured-controller-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unstructured-data-controller
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: unstructured-data-controller
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - /manager
        - --leader-elect
        - --health-probe-bind-address=:8081
        - --watch-namespace=$(WATCH_NAMESPACE)
        command:
        - /entrypoint.sh
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/redhat-data-and-ai/unstructured-data-controller:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports: []
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /data/cache
          name: unstructured-datastore-cache-storage
        - mountPath: /etc/pki/ca-trust/source/anchors
          name: custom-ca-certs
          readOnly: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: unstructured-controller-manager-test
      terminationGracePeriodSeconds: 10
      volumes:
      - name: unstructured-datastore-cache-storage
        persistentVolumeClaim:
          claimName: unstructured-datastore-cache-test
      - configMap:
          name: custom-ca-certs
          optional: true
        name: custom-ca-certs
