---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: unstructured-controller-namespace
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - chunksgenerators
  - controllerconfigs
  - destinationsyncers
  - documentprocessors
  - sourcecrawlers
  - unstructureddatapipelines
  - vectorembeddingsgenerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - chunksgenerators/finalizers
  - controllerconfigs/finalizers
  - destinationsyncers/finalizers
  - documentprocessors/finalizers
  - sourcecrawlers/finalizers
  - unstructureddatapipelines/finalizers
  - vectorembeddingsgenerators/finalizers
  verbs:
  - update
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - chunksgenerators/status
  - controllerconfigs/status
  - destinationsyncers/status
  - documentprocessors/status
  - sourcecrawlers/status
  - unstructureddatapipelines/status
  - vectorembeddingsgenerators/status
  verbs:
  - get
  - patch
  - update
