apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: VectorEmbeddingsGenerator
metadata:
  labels:
    app.kubernetes.io/name: unstructured-data-controller
    app.kubernetes.io/managed-by: kustomize
  name: vectorembeddingsgenerator-sample
spec:
  stageName: embed
  dependsOn:
    - name: chunk
  embeddingGeneratorConfig:
    modelName: nomic-ai/nomic-embed-text-v1.5
