apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: ControllerConfig
metadata:
  labels:
    app.kubernetes.io/name: unstructured-data-controller
    app.kubernetes.io/managed-by: kustomize
  name: controllerconfig
spec:
  secretRef: operator-secret
  doclingServeURL: "http://docling-serve:5001"
  dataStorageBucket: "data-storage-bucket"
  cacheDirectory: "tmp/cache/"
  maxConcurrentDoclingTasks: 5
  maxConcurrentLangchainTasks: 10
