apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: ChunksGenerator
metadata:
  labels:
    app.kubernetes.io/name: unstructured-data-controller
    app.kubernetes.io/managed-by: kustomize
  name: chunksgenerator-sample
spec:
  stageName: chunk
  dependsOn:
    - name: convert
  config:
    strategy: recursiveCharacterTextSplitter
    recursiveCharacterSplitterConfig:
      chunkSize: 1000
      chunkOverlap: 200
